version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 99
  assignees:
  - dsyncerek
  ignore:
  - dependency-name: concurrently
    versions:
    - 6.0.0
    - 6.0.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 99
  reviewers:
  - dsyncerek
  assignees:
  - dsyncerek
  ignore:
  - dependency-name: react-use
    versions:
    - 17.0.1
    - 17.1.0
    - 17.1.1
    - 17.2.1
    - 17.2.3
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: "@reduxjs/toolkit"
    versions:
    - 1.5.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: react-bootstrap
    versions:
    - 1.5.0
    - 1.5.1
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 99
  reviewers:
  - dsyncerek
  assignees:
  - dsyncerek
  ignore:
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.1
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: typeorm
    versions:
    - 0.2.30
  - dependency-name: class-transformer
    versions:
    - 0.3.2
