name: ClientCI

on:
  pull_request:
    paths:
      - 'client/**'
  push:
    branches:
      - master
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-client-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-client-npm-
      - working-directory: client
        run: npm ci
      - working-directory: client
        run: npm run lint
      - working-directory: client
        run: npm run test
      - working-directory: client
        run: npm run build
